// Regenerates `src/version.ts` from package.json so the CDN fallback in
// browser.ts pins the exact published version. Runs at the start of
// `build:ts` (and therefore `build`) so a bare `tsc` / editor still needs
// one generate, but `npm run build:ts` is self-sufficient. The file is
// gitignored — committing it made every version-bumped build dirty.

import { join } from 'node:path';

const pkgPath = join(import.meta.dir, '..', 'package.json');
const { version } = await Bun.file(pkgPath).json();

const contents = `// Auto-generated by scripts/generate-version.ts from package.json — do not
// edit; regenerated on every build.
export const VERSION = "${version}";
`;

await Bun.write(join(import.meta.dir, '..', 'src', 'version.ts'), contents);
console.log(`generate-version: src/version.ts -> ${version}`);
