// Regenerates `src/version.ts` from package.json so the CDN fallback in
// browser.ts pins the exact published version. Runs as part of `build`
// (before `build:ts`). The file is gitignored — committing it made every
// `npm run build` on a version-bumped branch leave a dirty working tree.

import { join } from 'node:path';

const pkgPath = join(import.meta.dir, '..', 'package.json');
const { version } = await Bun.file(pkgPath).json();

const contents = `// Auto-generated by scripts/generate-version.ts from package.json — do not
// edit; regenerated on every build.
export const VERSION = "${version}";
`;

await Bun.write(join(import.meta.dir, '..', 'src', 'version.ts'), contents);
console.log(`generate-version: src/version.ts -> ${version}`);
