// Generates `target/web/superscript_bg_inline.js` (+ .d.ts): the web-target
// wasm binary as a base64 string. Imported lazily by `src/browser.ts` as a
// fallback for bundlers without WebAssembly ESM integration (Bun, esbuild),
// where the `--target bundler` glue fails at import time. Run after
// `build:wasm:web`, before `build:ts`.

import { join } from 'node:path';

const webDir = join(import.meta.dir, '..', 'target', 'web');
const wasmPath = join(webDir, 'superscript_bg.wasm');

const bytes = await Bun.file(wasmPath).arrayBuffer();
const base64 = Buffer.from(bytes).toString('base64');

const js = `// Auto-generated by scripts/inline-wasm.ts — do not edit.
// Base64 of superscript_bg.wasm (web target) for bundler-agnostic loading.
export const wasmBase64 =
    "${base64}";
`;

const dts = `// Auto-generated by scripts/inline-wasm.ts — do not edit.
export declare const wasmBase64: string;
`;

await Bun.write(join(webDir, 'superscript_bg_inline.js'), js);
await Bun.write(join(webDir, 'superscript_bg_inline.d.ts'), dts);

console.log(
    `inline-wasm: wrote superscript_bg_inline.js (${(base64.length / 1024 / 1024).toFixed(2)} MB base64 from ${(bytes.byteLength / 1024 / 1024).toFixed(2)} MB wasm)`
);
